---
consul:
  enable: false
  address: 127.0.0.1:8501
  datacenter: dc1
  scheme: https
  token: YOUR-CONSUL-ACL-TOKEN
  tls:
    enable: true
    insecure_skip_verify: true
    ca_file: ssl/ca.pem
    cert_file: ssl/client.pem
    key_file: ssl/client-key.pem
