---
EncryptKey: true

Users:
  admin:
    email: admin@appmesh.com
    exec_user: ""
    group: admin
    key: $pbkdf2$100000$104d24c65e1095a363e2ba82885825c7$e070fe2ece1aceebf8d5ef66d03ba58483925113a07558b226bb604fb9d50616
    locked: false
    mfa_enabled: false
    mfa_key: ""
    roles:
      - manage
      - view
      - shell
      - usermgr
  mesh:
    email: mesh@appmesh.com
    exec_user: ""
    group: user
    key: $pbkdf2$100000$805b5735085f625281e076d773a08610$f56efc9d5e244cc8b32cbbbb3956ef3271d3866eb02469c51c6daa5d10207e04
    locked: false
    roles:
      - view
  test:
    email: test@appmesh.com
    exec_user: appmesh
    group: user
    key: $pbkdf2$100000$5349b9a29bfabf7c0aebba6ae8d4d533$998197cb44b68777ac128c5b81229b5e5d18dee3306ef7ae2a82c492aab65a42
    locked: false
    roles: []

Roles:
  manage:
    - app-control
    - app-delete
    - app-reg
    - app-subscribe
    - config-set
    - file-download
    - file-upload
    - label-delete
    - label-set
  shell:
    - app-run-async
    - app-run-sync
    - app-run-task
  usermgr:
    - user-add
    - passwd-change-user
    - user-delete
    - user-lock
    - role-delete
    - role-set
    - user-totp-disable
    - user-unlock
  view:
    - config-view
    - label-view
    - role-view
    - user-list
    - permission-list
    - passwd-change-self
    - app-view-all
    - app-view
    - app-output-view
    - user-totp-active
    - user-token-renew
    - host-resource-view
