---
EncryptKey: true

Users:
  admin:
    email: admin@appmesh.com
    exec_user: ""
    group: admin
    key: H17197393981645110028
    locked: false
    mfa_enabled: false
    mfa_key: ""
    roles:
      - manage
      - view
      - shell
      - usermgr
  mesh:
    email: mesh@appmesh.com
    exec_user: ""
    group: user
    key: H15079608314932066436
    locked: false
    roles:
      - view
  test:
    email: test@appmesh.com
    exec_user: appmesh
    group: user
    key: H15910623431124983003
    locked: false
    roles: []

Roles:
  manage:
    - app-control
    - app-delete
    - app-reg
    - config-set
    - file-download
    - file-upload
    - label-delete
    - label-set
  shell:
    - app-run-async
    - app-run-sync
  usermgr:
    - user-add
    - passwd-change-user
    - user-delete
    - user-lock
    - role-delete
    - role-set
    - user-totp-disable
    - user-unlock
  view:
    - config-view
    - label-view
    - role-view
    - user-list
    - permission-list
    - passwd-change-self
    - app-view-all
    - app-view
    - app-output-view
    - user-totp-active
    - user-token-renew
    - host-resource-view
