BaseConfig:
  # A short, descriptive name for this host, such as ENV-ROLE-NUMBER (e.g., PROD-WEB-001).
  Description: MYHOST

  # The default operating system user for app execution. This user will be used when no specific execution user is provided.
  DefaultExecUser: ""

  # When true, all applications will run under the AppMesh systemd user instead of individual users.
  # Applications will follow the appmesh systemd user set during installation (APPMESH_DAEMON_EXEC_USER/APPMESH_DAEMON_EXEC_USER_GROUP).
  DisableExecUser: false

  # Interval (in seconds) for application health checks.
  # Increase this value if frequent checks are unnecessary.
  ScheduleIntervalSeconds: 1

  # Working directory for AppMesh, with a default of /opt/appmesh/work.
  WorkingDirectory: ""

  # Log level for the system (available options: DEBUG, INFO, NOTICE, WARN, ERROR).
  LogLevel: INFO

  # Time zone setting for AppMesh logs, in POSIX format.
  PosixTimezone: "+08"

REST:
  # Enables or disables the REST API interface.
  RestEnabled: true

  # Address for REST API access.
  # Use "localhost" for local access only, or "0.0.0.0" to allow external access.
  RestListenAddress: 127.0.0.1

  # HTTP port for the REST API.
  RestListenPort: 6060

  # TCP port for the TCP API.
  RestTcpPort: 6059

  # Port for Prometheus metrics export.
  # To enable metrics collection, set to a specific port (e.g., 9091).
  PrometheusExporterListenPort: 0

  # Number of threads to handle HTTP requests.
  # Increase this number based on expected concurrent load.
  HttpThreadPoolSize: 2

  # JWT Authentication Configuration
  JWT:
    # Salt for JWT token generation. IMPORTANT: Change this in production.
    JWTSalt: HelloAppMesh

    # JWT sign algorithm (HS256,RS256).
    # - HS256 use JWTSalt as secret
    # - RS256 use public/private key pair in ssl directory
    # - SS256 use ECDS public/private key pair in ssl directory
    Algorithm: HS256

    # Name of the JWT token issuer, typically set to your organization or service name.
    # Defaults to the hostname if left empty.
    Issuer: ""

    # Audience for the JWT token.
    Audience: ["appmesh-service", "your-service-api"]

    # Authentication type to use [local/ldap/consul/oauth2].
    SecurityInterface: local

  SSL:
    # Path to the Certificate Authority (CA) certificate.
    SSLCaPath: ssl/ca.pem

    # Server certificate (chain) and private key file paths.
    SSLCertificateFile: ssl/server.pem
    SSLCertificateKeyFile: ssl/server-key.pem

    # Client certificate and private key file paths.
    SSLClientCertificateFile: ssl/client.pem
    SSLClientCertificateKeyFile: ssl/client-key.pem

    # Enables or disables verification of client certificates.
    VerifyClient: false

    # Enables or disables verification of server certificates.
    VerifyServer: true

    # Enables or disables delegated server verification.
    VerifyServerDelegate: false

# Node labels with 2 default samples provided.
Labels:
  arch: x86_64
  os_version: centos7.6
