---
BaseConfig:
  # A brief description for this host
  Description: MYHOST
  # Default app execution OS user name
  DefaultExecUser: ""
  # When true, all apps use the appmesh systemd user instead of individual execution users
  # Apps will follow appmesh systemd user (set by installation env: APPMESH_DAEMON_EXEC_USER/APPMESH_DAEMON_EXEC_USER_GROUP)
  DisableExecUser: false
  # Schedule interval (in seconds) for application error handling
  ScheduleIntervalSeconds: 1
  # Working directory for appmesh
  WorkingDirectory: ""
  # Log level (options: DEBUG, INFO, NOTICE, WARN, ERROR)
  LogLevel: INFO
  # Timezone for appmesh output (default: server's timezone)
  PosixTimezone: "+08"

REST:
  RestEnabled: true
  RestListenAddress: localhost
  RestListenPort: 6060
  RestTcpPort: 6059

  PrometheusExporterListenPort: 0
  DockerProxyListenAddr: ""
  HttpThreadPoolSize: 2
  JWT:
    JWTSalt: HelloAppMesh
    Issuer: ""
    SecurityInterface: local

  SSL:
    SSLCaPath: /opt/appmesh/ssl/ca.pem
    SSLCertificateFile: /opt/appmesh/ssl/server.pem
    SSLCertificateKeyFile: /opt/appmesh/ssl/server-key.pem
    SSLClientCertificateFile: /opt/appmesh/ssl/client.pem
    SSLClientCertificateKeyFile: /opt/appmesh/ssl/client-key.pem
    VerifyClient: false
    VerifyServer: true
    VerifyServerDelegate: false

Consul:
  AppmeshProxyUrl: ""
  EnableConsulSecurity: false
  IsMainNode: true
  IsWorkerNode: true
  Pass: ""
  SessionTTL: 30
  Url: ""
  User: ""

Labels:
  arch: x86_64
  os_version: centos7.6
