FROM ubuntu:24.04@sha256:4fbb8e6a8395de5a7550b33509421a2bafbc0aab6c06ba2cef9ebffbc7092d90

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_build_deps.apt.sh && rm -rf /workspace/*
