FROM debian:13@sha256:913f6706df59a68922d1dd08f78c2476560a8d367897200a6005b00e5f67c2d5

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_build_deps.apt.sh && rm -rf /workspace/*
