FROM centos:7@sha256:be65f488b7764ad3638f236b7b515b3678369a5124c47b8d32916d6487418ea4

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/setup_build_env/update_openssl.sh && bash script/setup_build_env/autogen.sh && rm -rf /workspace/*
