FROM debian:13@sha256:9cc080028c43b27d2074d63a5f9caf7166d731494965616c1a6d2827a004585c

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_build_deps.apt.sh && rm -rf /workspace/*
