FROM ubuntu:26.04@sha256:f144425ff09be612d6d9ad965196e9cdc23dae1f42110a8a11a3e9a8198759f7

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_openssl.sh && bash script/bootstrap/install_build_deps.sh && rm -rf /workspace/*
