FROM ubuntu:24.04@sha256:69cecf4bbf72d2d44a9eef1b71fb98c7fb973d78af11399deccef19beb008ad9

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_openssl.sh && bash script/bootstrap/install_build_deps.sh && rm -rf /workspace/*
