FROM ubuntu:22.04@sha256:4f838adc7181d9039ac795a7d0aba05a9bd9ecd480d294483169c5def983b64d

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_openssl.sh && bash script/bootstrap/install_build_deps.sh && rm -rf /workspace/*
