FROM python:3.14.5-slim-bookworm@sha256:a3974109d36f164ca70024bc0d0828ac706e4ccda849f8638d879e91f79e90ec AS build_stage

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create and set working directory
WORKDIR /appmesh

# Install system dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN python -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir appmesh && \
    wget --no-check-certificate https://raw.githubusercontent.com/laoshanxi/app-mesh/main/src/cli/appmesh_agent.py -P /appmesh/

FROM python:3.14.5-slim-bookworm@sha256:a3974109d36f164ca70024bc0d0828ac706e4ccda849f8638d879e91f79e90ec

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy virtual environment from the build stage
COPY --from=build_stage /opt/venv /opt/venv
COPY --from=build_stage /appmesh/appmesh_agent.py /appmesh/

# Set PATH to include Python venv binary
ENV PATH="/opt/venv/bin:$PATH"

# Set working directory
WORKDIR /appmesh

# Run your application
ENTRYPOINT ["python3", "appmesh_agent.py"]
