FROM ubuntu:25.10@sha256:7cc5e35f6567ee8c66d2abb4aab0fd866669e6207c237c3a8f0947a5c7f17092

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_build_deps.apt.sh && rm -rf /workspace/*
