FROM ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_openssl.sh && bash script/bootstrap/install_build_deps.sh && rm -rf /workspace/*
