FROM ubuntu:24.04@sha256:786a8b558f7be160c6c8c4a54f9a57274f3b4fb1491cf65146521ae77ff1dc54

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/bootstrap/install_build_deps.apt.sh && rm -rf /workspace/*
