FROM ubuntu:22.04@sha256:eb29ed27b0821dca09c2e28b39135e185fc1302036427d5f4d70a41ce8fd7659

WORKDIR /workspace

COPY . /workspace/

USER root

RUN bash script/setup_build_env/update_openssl.sh && bash script/setup_build_env/autogen.sh && rm -rf /workspace/*
