name: appmesh_cluster
services:
  appmesh_master:
    hostname: appmesh_master
    container_name: appmesh_master
    restart: always
    image: laoshanxi/appmesh
    environment:
      - APPMESH_REST_PrometheusExporterListenPort=6061
    ports:
      - "443:443" # for appmesh_ui
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  appmesh_ui:
    restart: always
    image: laoshanxi/appmesh-ui
    depends_on:
      - appmesh_master
    network_mode: "service:appmesh_master"

  appmesh_slave1:
    hostname: appmesh_slave1
    container_name: appmesh_slave1
    restart: always
    image: laoshanxi/appmesh
    mem_limit: 4G
    environment:
      - APPMESH_REST_PrometheusExporterListenPort=6061
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  appmesh_slave2:
    hostname: appmesh_slave2
    container_name: appmesh_slave2
    restart: always
    image: laoshanxi/appmesh
    mem_limit: 3G
    environment:
      - APPMESH_REST_PrometheusExporterListenPort=6061
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  appmesh_slave3:
    hostname: appmesh_slave3
    container_name: appmesh_slave3
    restart: always
    image: laoshanxi/appmesh
    mem_limit: 3G
    environment:
      - APPMESH_REST_PrometheusExporterListenPort=6061
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
