server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /opt/appmesh/work/stdout/*.out

  - job_name: appmesh
    static_configs:
      - targets:
          - localhost
        labels:
          job: appmesh
          __path__: /opt/appmesh/work/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) \[(?P<thread_id>\d+)\] (?P<level>\w+) : (?P<message>.*)$'
      - labels:
          level:
          thread_id:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
