global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "appmesh"
    scrape_interval: 10s
    static_configs:
      - targets: ["appmesh_node:6061"]

# rules.yml for alert manager
rule_files:
  - "rules.yml"

# alert manager configuration
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ["alertmanager:9093"]
