name: "Build Centos 8 Build Image"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-centos-8.yml"
      - "docker/Dockerfile.build_centos8"
      - "script/setup_build_env/autogen.sh"

env:
  REGISTRY: docker.io
  IMAGE_NAME: laoshanxi/appmesh

permissions:
  contents: read

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout Github code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.build_centos8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build_centos8
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build_centos8
          cache-to: type=inline
          provenance: false
