name: "Code scan with Coverity"

on:
  # trigger when code changes
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/coverity_cpp_code_scan.yml"

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

env:
  APPMESH_VERSION: "2.1.1"

jobs:
  coverity-cpp-code-scan:
    runs-on: ubuntu-latest
    container: laoshanxi/appmesh:build_ubuntu22

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Github code
        uses: actions/checkout@v3

      - name: Cmake init with Debug mode
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..

      # https://github.com/vapier/coverity-scan-action
      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          project: laoshanxi%2Fapp-mesh
          working-directory: build
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          email: 178029200@qq.com
          version: ${{ env.APPMESH_VERSION }}
