name: Coverity CPP code scan

on:
  # trigger when code changes
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/coverity_cpp_code_scan.yml"

env:
  APPMESH_VERSION: "2.1.1"

jobs:
  coverity-cpp-code-scan:
    runs-on: ubuntu-latest
    container: laoshanxi/appmesh:build_ubuntu22

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Github code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup curl
        run: apt-get install --fix-missing -y curl

      - name: Cmake init with Debug mode
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..

      # https://github.com/laoshanxi/coverity-scan-action
      - name: Coverity scan
        uses: laoshanxi/coverity-scan-action@4fa81d9a897165dff6167e2930d62a6860ee66ce # v1
        with:
          project: laoshanxi%2Fapp-mesh
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          email: 178029200@qq.com
          version: ${{ env.APPMESH_VERSION }}
          description: "Ubuntu 9.3.0-17ubuntu1~20.04"
