name: "Upload python SDK to PyPI"

on:
  push:
    branches:
      - main
    paths:
      - "src/sdk/python/**"
      - ".github/workflows/python-sdk-twine-upload.yml"

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install twine wheel requests

      - name: Build package
        run: python setup.py bdist_wheel
        working-directory: src/sdk/python

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: src/sdk/python/dist
# https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
