name: Publish PyPI SDK package

on:
  push:
    branches:
      - main
    paths:
      - "src/sdk/python/**"
      - .github/workflows/release-pypi-package.yml

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout Github code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install twine wheel requests

      - name: Build package
        run: python setup.py bdist_wheel
        working-directory: src/sdk/python

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: src/sdk/python/dist
# https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
