name: publish-pypi-package

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/sdk/python/**"
      - .github/workflows/release-pypi-package.yml

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout Github code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build setuptools
          pip install twine wheel requests

      - name: Build package
        run: |
          python -m build --wheel --outdir dist
        working-directory: src/sdk/python

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: src/sdk/python/dist
# https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
