name: "release-sdk-rust"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/sdk/rust/**"

permissions: read-all

jobs:
  build-and-release:
    name: Build and Release Rust SDK
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: src/sdk/rust

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Cache Cargo
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build (release)
        run: cargo build --release
        env:
          # Prevent compiler warnings from being treated as errors
          RUSTFLAGS: ""
          CI: true

      #- name: Run tests
      #  run: cargo test --release --all

      - name: Verify publish
        run: cargo publish --dry-run --allow-dirty

      - name: Publish to crates.io
        run: cargo publish --no-verify --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
