name: "test_CI"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-ci.yml
  workflow_run:
    workflows: ["release_github_package"]
    types: [completed]

env:
  APPMESH_VERSION: "2.1.2"

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ci-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: test ubuntu:18
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: ubuntu:18.04
          options: -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            apt update
            apt install -y wget iputils-ping
            wget --quiet --no-check-certificate https://github.com/laoshanxi/app-mesh/releases/download/${{ env.APPMESH_VERSION }}/appmesh_2.1.2_gcc_7_glibc_2.27_x86_64.deb
            apt install -y ./appmesh_*.deb

            # start appmesh
            /opt/appmesh/script/appmesh-entrypoint.sh &
            sleep 5
            appc ls

            # test appmesh golang sdk
            apt install -y wget
            GO_ARCH=amd64
            GO_VER=1.21.5
            wget https://golang.org/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz >/dev/null 2>&1
            tar -C /usr/local -xzf go${GO_VER}.linux-${GO_ARCH}.tar.gz
            cd /work/src/sdk/go
            /usr/local/go/bin/go test -v

            # test appmesh python sdk
            apt install -y python3 python3-pip
            python3 -m pip install --upgrade appmesh pyotp
            cd /work/test/python
            python3 -m unittest

      - name: test ubuntu:22
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: ubuntu:22.04
          options: -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            apt update
            apt install -y wget iputils-ping
            wget --quiet --no-check-certificate https://github.com/laoshanxi/app-mesh/releases/download/${{ env.APPMESH_VERSION }}/appmesh_2.1.2_gcc_11_glibc_2.35_x86_64.deb
            apt install -y ./appmesh_*.deb

            # start appmesh
            /opt/appmesh/script/appmesh-entrypoint.sh &
            sleep 5
            appc ls

            # test appmesh golang sdk
            apt install -y wget
            GO_ARCH=amd64
            GO_VER=1.21.5
            wget https://golang.org/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz >/dev/null 2>&1
            tar -C /usr/local -xzf go${GO_VER}.linux-${GO_ARCH}.tar.gz
            cd /work/src/sdk/go
            /usr/local/go/bin/go test -v

            # test appmesh python sdk
            apt install -y python3 python3-pip
            python3 -m pip install --upgrade appmesh pyotp
            cd /work/test/python
            python3 -m unittest

      - name: test ubuntu:24
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: ubuntu:24.04
          options: -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            apt update
            apt install -y wget iputils-ping
            wget --quiet --no-check-certificate https://github.com/laoshanxi/app-mesh/releases/download/${{ env.APPMESH_VERSION }}/appmesh_2.1.2_gcc_13_glibc_2.39_x86_64.deb
            apt install -y ./appmesh_*.deb

            # start appmesh
            /opt/appmesh/script/appmesh-entrypoint.sh &
            sleep 5
            appc ls

            # test appmesh golang sdk
            apt install -y wget
            GO_ARCH=amd64
            GO_VER=1.21.5
            wget https://golang.org/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz >/dev/null 2>&1
            tar -C /usr/local -xzf go${GO_VER}.linux-${GO_ARCH}.tar.gz
            cd /work/src/sdk/go
            /usr/local/go/bin/go test -v

            # test appmesh python sdk
            apt install -y python3 python3-pip
            python3 -m pip install --break-system-packages --upgrade appmesh pyotp
            cd /work/test/python
            python3 -m unittest

      - name: test centos:7
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: centos:7
          options: -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            # centos 7
            cp -a /etc/yum.repos.d /etc/yum.repos.d.backup
            rm -f /etc/yum.repos.d/*.repo
            curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
            yum clean all
            yum makecache

            yum install -y https://github.com/laoshanxi/app-mesh/releases/download/${{ env.APPMESH_VERSION }}/appmesh_2.1.2_gcc_4.8.5_glibc_2.17_x86_64.rpm

            # start appmesh
            /opt/appmesh/script/appmesh-entrypoint.sh &
            sleep 5
            appc ls

            # test appmesh golang sdk
            yum install -y wget
            GO_ARCH=amd64
            GO_VER=1.21.5
            wget https://golang.org/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz >/dev/null 2>&1
            tar -C /usr/local -xzf go${GO_VER}.linux-${GO_ARCH}.tar.gz
            cd /work/src/sdk/go
            /usr/local/go/bin/go test -v

            # test appmesh python sdk
            yum install -y python3 python3-pip
            python3 -m pip install --upgrade appmesh pyotp
            cd /work/test/python
            python3 -m unittest
